apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"  # 10% 트래픽
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.porticard.kro.kr
    secretName: porticard-tls
  rules:
  - host: www.porticard.kro.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service-canary
            port:
              number: 80